// react/pre-flight-checklist/src/components/login.js
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import Group4 from '../assets/Group 4.png';
import './signup-login.css';

const Login = () => {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const navigate = useNavigate();

  const handleLogin = async () => {
    try {
      
      
      if (username && password) {
        
        const token = 'ad9acff274e64cde5c771a0447906e8e7879a65c';
        localStorage.setItem('authToken', token);
        localStorage.setItem('username', username);
        navigate('/dashboard'); 
      } else {
        setError('Please enter username and password');
      }
    } catch (error) {
      console.error('Error logging in:', error);
      setError('Login failed. Please try again.');
    }
  };

  return (
    <div className="flex min-h-screen bg-gradient-to-br from-indigo-600 via-purple-600 to-pink-600">
      {/* Image Section */}
      <div className="hidden md:flex md:w-1/2 items-center justify-center p-8">
        <div className="bg-white/10 backdrop-blur-md rounded-3xl p-8">
          <img src={Group4} alt="Log in" className="w-full h-auto rounded-2xl shadow-2xl" />
        </div>
      </div>

      {/* Form Section */}
      <div className="flex flex-col justify-center items-center md:w-1/2 w-full p-6">
        <div className="w-full max-w-md">
          {/* Header */}
          <div className="text-center mb-8">
            <h1 className="text-4xl font-bold text-white mb-2">Welcome Back</h1>
            <p className="text-white/80">Sign in to your account</p>
          </div>

          {/* Card */}
          <div className="bg-white rounded-2xl shadow-2xl p-8">
            {error && (
              <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-lg">
                <p className="text-red-600 text-sm font-medium">{error}</p>
              </div>
            )}

            <form
              onSubmit={(e) => {
                e.preventDefault();
                handleLogin();
              }}
            >
              <div className="mb-6">
                <label className="block text-gray-700 text-sm font-semibold mb-3" htmlFor="username">
                  Username
                </label>
                <input
                  className="w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-indigo-500 focus:outline-none transition duration-200"
                  id="username"
                  type="text"
                  placeholder="Enter your username"
                  value={username}
                  onChange={(e) => {
                    setUsername(e.target.value);
                    setError('');
                  }}
                  required
                />
              </div>

              <div className="mb-6">
                <label className="block text-gray-700 text-sm font-semibold mb-3" htmlFor="password">
                  Password
                </label>
                <input
                  className="w-full px-4 py-3 border-2 border-gray-200 rounded-lg focus:border-indigo-500 focus:outline-none transition duration-200"
                  id="password"
                  type="password"
                  placeholder="Enter your password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  required
                />
              </div>

              <button
                className="w-full btn-primary mb-4"
                type="submit"
              >
                Sign In
              </button>
            </form>

            <div className="text-center mt-6">
              <p className="text-gray-600 text-sm">
                Don't have an account? <a href="/signup" className="text-indigo-600 font-semibold hover:text-indigo-700">Sign up</a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Login;

// projet fin d'etude/bitchest/Frontend/src/views/Login.vue
<template>
  <div v-if="loading" class="text-center w-full">
    <Loader />
  </div>
  <div v-else>
    <div class="flex items-center justify-center min-h-screen bg-gray-100">
      <div class="bg-white p-8 rounded-lg shadow-lg w-96">
        <h2 class="text-2xl font-bold text-center mb-4 text-gray-700">Login</h2>

        <form @submit.prevent="handleLogin" class="space-y-4">
          <!-- Email Input -->
          <div>
            <label class="block text-gray-600 text-sm mb-1">Email</label>
            <input
              v-model="email"
              type="email"
              placeholder="Enter your email"
              autocomplete="email"
              required
              class="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-400"
            />
          </div>

          <!-- Password Input -->
          <div>
            <label class="block text-gray-600 text-sm mb-1">Password</label>
            <input
              v-model="password"
              type="password"
              placeholder="Enter your password"
              autocomplete="current-password"
              required
              class="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-400"
            />
          </div>

          <!-- Login Button -->
          <button
            type="submit"
            class="w-full bg-bitchest-success text-[1rem] text-black font-bold px-6 py-2 mb-5 rounded-md hover:bg-gray-200"
          >
            Login
          </button>
        </form>
      </div>
    </div>
  </div>
</template>

<script>
import { mapActions } from "vuex";
import { useToast } from "vue-toastification";
import NavBar from "../components/NavBar.vue";
import Loader from "@/components/utils/Loader.vue";

export default {
  components: {
    NavBar,
    Loader,
  },
  data() {
    return {
      email: "",
      password: "",
      loading: false,
    };
  },
  setup() {
    const toast = useToast();
    return { toast };
  },
  methods: {
    ...mapActions("auth", ["login"]),
    async handleLogin() {
      this.loading = true;
      try {
        const response = await this.login({
          email: this.email,
          password: this.password,
        });

        // ✅ Check if login was successful
        if (response && response.token) {
          const user = response.user;

          if (user.role === "client" && user.email_verified_at === null) {
            // To be modified
            this.toast.warning("Please complete your profile.");
            setTimeout(() => this.$router.push("/complete-profile"), 100);
          } else {
            this.toast.success("Login successful!");
            setTimeout(() => this.$router.push("/dashboard"), 100);
          }
        } else {
          throw new Error("Invalid login credentials");
        }
      } catch (error) {
        this.toast.error("Login failed. Please check your credentials.");
      } finally {
        this.loading = false;
      }
    },
  },
};
</script>
